### ISSUE TITLE
Fail to insert module

### ISSUE THREAD

**Issue by eecheng87** [c-blake/batch#2]
Hi, first of all, thanks for your interesting works.
I tried to follow command you mentioned in README but I got `Killed` when I insert module `batch`.
Following is part of message in `dmesg`:
```
[ 1503.506082] batch: loading out-of-tree module taints kernel.
[ 1503.506206] batch: module verification failed: signature and/or required key missing - tainting kernel
[ 1503.507107] BUG: unable to handle page fault for address: ffffffff82000878
[ 1503.507117] #PF: supervisor read access in kernel mode
[ 1503.507122] #PF: error_code(0x0000) - not-present page
```
I'm using Ubuntu 20.04 and kernel version is 5.9.12-050912-generic.

Any suggestions would be greatly appreciated!

**Comment by c-blake** [comment]
You're welcome.

Hmm.  It works for me on 5.9.*, but I build my own kernels.  I did test against some older Debian 4.x series installs as virtual images, though.  The mainline Linux guys have been making it trickier over the decades to install a new system call via a module.

The faulting address looks a lot like what the `Makefile` might get when creating `scTab.h` { you can confirm via `grep -w sys_call_table /boot/System.map-$(uname -r)` }, but it is important that the `System.map` match the kernel you will be doing the `insmod` against, not merely its version string.  If that is not the problem, then there may be some "kernel CONFIG_" setting in your kernel that interferes with what I do to alter the system call table.

We may be able to figure out which of these two possibilities is the problem if you have the ability to run on a 5.6.* or earlier kernel (which can just `kallsyms_lookup_name` assuming said 5.6.* kernel has `CONFIG_KALLSYMS` & `CONFIG_KALLSYMS_ALL` turned on).  Another possibility might be that you are not running on an x86_64/amd64 CPU.

**Comment by c-blake** [comment]
This probably won't help with the page fault problem (since the kernel seems to run the module code in spite of its being unsigned), but you can also probably get rid of those those module verification errors via steps mentioned [here](https://askubuntu.com/questions/483283/module-verification-failed-signature-and-or-required-key-missing).

**Comment by c-blake** [comment]
I just re-built a 5.9.12 stock Linux and it worked both on an AMD processor and an Intel processor.  So, the mainline kernel guys have not added anything that interferes.

If it is not a System.map-vs-running kernel mismatch or a CONFIG_ setting or non-x86_64 then a fourth possibility is that it could be Ubuntu-specific kernel patches.  I know many distros have little patches they apply to the kernel from time to time.

If none of this gets you going, to collaborate on an answer, we would probably have to pick some image at [osboxes](https://www.osboxes.org/virtualbox-images/) to try to get working.  I might just proactively select one, but there are like 7 Ubuntu variants.

**Comment by eecheng87** [comment]
Thanks for your quick reply.
> This probably won't help with the page fault problem
Did you reject first one possibility you mentioned? BTW, `scTab` was defined as 0xffffffff820002c0UL in my case, which is differ from page fault address: ffffffff82000878. Did this imply mismatch with kernel?

>  I just re-built a 5.9.12 stock Linux and it worked both on an AMD processor and an Intel processor. So, the mainline kernel guys have not added anything that interferes.
Again, did you reject the second possibility you mentioned?

**Comment by c-blake** [comment]
Well, we actually install the syscall via something like `syscalltab[__NR_batch = _NR_afs_syscall] = our_code`. The slot I take is that of the now unused/vestigial `_NR_afs_syscall` which is `183`, usually. `183*8 = 1464` and that is exactly how many bytes your two addresses differ by.  So, that all makes sense.

The fault is almost surely where we try to update the syscall table to point to `sys_batch`, but that may be invalid memory from a System.map-kernel build mismatch.  That's what it most looks like to me, but then the question is what, on your system, happens to produce that mismatch.

That is just more explanation.  I don't think any possibilities have been eliminated so far.

**Comment by eecheng87** [comment]
After logging some messages, I'm pretty sure it crash at `sys_oldcall0 = scTab[__NR_batch];`.

**Comment by c-blake** [comment]
Yeah.  Failing at the read before the write also makes sense if the base address (`scTab`) is somehow wrong.  Since I cannot reproduce the failure in my environments, I may need some more details from you about your Ubuntu and/or a pointer to one of those OSBoxes images that exhibits a similar failure.

For me, that (base) address is `0xffffffff82600240UL` (so the implied fault address which I do *not* get a fault for would be `0xffffffff826007f8`, but I expect that it's normal for a bunch of kernel CONFIG_ changes to alter the address a little.  In this case they are only 128 bytes shifted.

I think if we can get the right scTab value for you then it will work.  `CONFIG_RANDOMIZE_BASE` does sound like it may be the root cause.  I do not have that in my kernel `.config`, also available in `/proc/config.gz`).  I also do not have RELOCATABLE_KERNEL at all.

**Comment by c-blake** [comment]
Is configuring/building a new kernel from [kernel.org](https://www.kernel.org/) or Ubuntu sources or whatever within your skillset?  If so, doing that with a non-relocatable kernel is probably the easiest way to get going.

Otherwise we need to track down how to lookup the "random shift" and put that in the module (probably conditioned upon the CONFIG_ setting).

**Comment by c-blake** [comment]
Also, if it is actually random seeded by something in the world like a CPU RNG/time/etc. then we will want to reboot at least once to be sure we got it.  Thanks for helping on this.  `sys_batch` has not been deployed on many kernel builds. There are probably 5000 CONFIG_ settings by now. :-)

**Comment by c-blake** [comment]
Well, I configured with `RELOCATABLE` & `RANDOMIZE_BASE` and reproduced your failure.  Now I just need to figure out how to find the shift at module load time.  (But you can at least "kick the tires" on this proof-of-concept thing if you can re-config your own kernel or download one without those turned on.)

**Comment by c-blake** [comment]
It looks like you can also just reboot with `nokaslr` (either by manually intervening upon bootup and adding that kernel command line parameter or by adding it in your Grub config).

**Comment by c-blake** [comment]
Well, for me it now works both with and without `nokaslr` on the kernel command line.  Let me know if this works/does not work for you and I can re-open the issue if it is still failing.

**Comment by eecheng87** [comment]
Hi, sorry for late reply and thanks for your help.
I turn off kalsr by adding parameter `nokalsr` and reboot, `batch` finally can be inserted. Cheers!

**Comment by c-blake** [comment]
Cool.  Glad to hear you got it going.  If you git pull/re-git clone the latest then you should also be able to use it with or without `nokaslr`.  Cheers to you as well!

**Comment by eecheng87** [comment]
Thanks for your quick reply and fixing, it becomes more convenient (at least for me :-) ).

**Comment by c-blake** [comment]
You're welcome.  It's honestly probably a pretty common problem, not just you. :-)
