### ISSUE TITLE
Please add a License file

### ISSUE THREAD

**Issue by pPanda-beta** [c-blake/batch#4]
Adding license file helps tech giants like Google, Microsoft, Meta, ...etc to import and contribute to this Kmodule without worrying much legally.

**Comment by c-blake** [comment]
I really kind of doubt tech giants will use this no matter the license since it stopped working on Linux-6.9 as noted in the README, but do you have a recommended license for such?

**Comment by pPanda-beta** [comment]
It can still be used in previous kernels. When it comes to stat 1B+ files on ext4, significant amount of time can be saved if we use batch syscalls.

**Comment by c-blake** [comment]
>It can still be used in previous kernels.

I am unsure how you think I could possibly be unaware of that since I just said it or be unaware of the utility when I have the various benchmark programs to specifically assess it.  I merely meant "since there seems no path forward without significant internal re-working, big tech probably doesn't care".  They probably don't anyway is the truth, though they may make a license excuse.

Also, `io_uring` handles `stat`.

With no specific recommended license, I am closing this issue.
